# Default color theme.
#
# Import the standard colors.
source ~/.dotfiles/bash/themes/basecolors.sh

PROMPT_DEFAULT_COLOR=$COLOR_LIGHT_GRAY
PROMPT_USER_DEFAULT_COLOR=$COLOR_PURPLE
PROMPT_USER_ROOT_COLOR="[31;40m"
PROMPT_HOST_LOCAL_COLOR=$COLOR_BROWN
PROMPT_HOST_REMOTE_COLOR=$COLOR_RED
PROMPT_PATH_COLOR=$COLOR_GREEN
