# Based on Textmate's monokai theme.
#
# Import the standard colors.
source ~/.dotfiles/bash/themes/basecolors.sh

PROMPT_DEFAULT_COLOR=$COLOR_WHITE
PROMPT_USER_DEFAULT_COLOR=`EXT_COLOR 198`
PROMPT_USER_ROOT_COLOR=`EXT_COLOR 198`
PROMPT_HOST_LOCAL_COLOR=`EXT_COLOR 118`
PROMPT_HOST_REMOTE_COLOR=`EXT_COLOR 118`
PROMPT_PATH_COLOR=`EXT_COLOR 227`
